import Link from "next/link";
import DataProvider from "./_component/DataProvider";
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <DataProvider>
              <h1>Simple app</h1>
              <hr />
              <Link href="/">home</Link>&nbsp;&nbsp;&nbsp;&nbsp;
              <Link href="/input">input</Link>&nbsp;&nbsp;&nbsp;&nbsp;
              <Link href="/show">show</Link>
              <hr />
              {children}
          </DataProvider>
      </body>
    </html>
  )
}